#!/bin/bash
# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

if [ -n "$AWS_LAMBDA_FUNCTION_MEMORY_SIZE" ];
then
  new_space=$(expr $AWS_LAMBDA_FUNCTION_MEMORY_SIZE / 10)
  semi_space=$(expr $new_space / 2)
  old_space=$(expr $AWS_LAMBDA_FUNCTION_MEMORY_SIZE - $new_space)
  MEMORY_ARGS=(
    "--node-arg=--max-semi-space-size=$semi_space"
    "--node-arg=--max-old-space-size=$old_space"
  )
fi

# if [[ $AWS_DEFAULT_REGION == us-iso* ]]
# then export NODE_EXTRA_CA_CERTS="/etc/pki/tls/certs/ca-bundle.crt"
# fi

NODE_ARGS=(
    --no-install
    --node-arg=--expose-gc
    --node-arg=--max-http-header-size=81920
    "${MEMORY_ARGS[@]}"
    )

if [ -z "$AWS_LAMBDA_EXEC_WRAPPER" ]; then
  exec npx "${NODE_ARGS[@]}" aws-lambda-ric "${1}"
else
  wrapper="$AWS_LAMBDA_EXEC_WRAPPER"
  if [ ! -f "$wrapper" ]; then
    echo "$wrapper: does not exist"
    exit 127
  fi
  if [ ! -x "$wrapper" ]; then
    echo "$wrapper: is not an executable"
    exit 126
  fi
    exec -- "$wrapper" npx "${NODE_ARGS[@]}" aws-lambda-ric "${1}"
fi