api = "0.2"

[buildpack]
id = "jkutner/lambda"
version = "0.1.0"
name = "AWS Lambda Buildpack"

[[order]]
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "0.7.0"

  [[order.group]]
    id = "heroku/nodejs-npm"
    version = "0.4.0"

  [[order.group]]
    id = "jkutner/lambda-js"
    version = "0.1.0"
    optional = true